modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

logoFile="logo.png"

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

description='''
A mod developed by BirdSys.

This mod adds compact solutions for otherwise bulky Create: Aeronautics setups.

While this mod makes the setups for flying machines (Or whatever you come up with) easier, it lets you greatly compact a lot of contraptions.

If you have any use-case worth compacting as a Create simulated/non-simulated Block/s, write me an email detailing it [dartifact.contact@gmail.com] I MAY implement it.

No attachments!

'''

[[dependencies.create_tilting_control]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_tilting_control]]
    modId="create"
    type="required"
    versionRange="[6.0.10,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_tilting_control]]
    modId="aeronautics"
    type="required"
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_tilting_control]]
    modId="sable"
    type="required"
    versionRange="[2.0.0,3.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.create_tilting_control]]
    modId="simulated"
    type="required"
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"

